[main]
font=IosevkaTermSlab:size=16
width=40
lines=15

# Base16 Catppuccin Mocha
# Scheme author: https://github.com/catppuccin/catppuccin

# Base16 Catppuccin Latte
# Scheme author: https://github.com/catppuccin/catppuccin

# Base16 Nord Light
# Scheme author: 

# Base16 Nord Light
# Scheme author: 

# Base16 Tempus Dawn
# Scheme author: Protesilaos Stavrou (https://protesilaos.com)

# Base16 Papercolor Light
# Scheme author: 

# Base16 Lunaria Light
# Scheme author: 

# Base16 Hemisu Light
# Scheme author: 

# Base16 Ayu Light
# Scheme author: Tinted Theming (https://github.com/tinted-theming), Ayu Theme (https://github.com/ayu-theme)

# Base16 Gruvbox light, hard
# Scheme author: Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)

# Base16 Tokyo Night Light
# Scheme author: Michaël Ball

# Base16 Ayu Light
# Scheme author: Tinted Theming (https://github.com/tinted-theming), Ayu Theme (https://github.com/ayu-theme)

# Base16 Catppuccin Latte
# Scheme author: https://github.com/catppuccin/catppuccin

# Base16 Ayu Light
# Scheme author: Tinted Theming (https://github.com/tinted-theming), Ayu Theme (https://github.com/ayu-theme)

# Base16 Ayu Light
# Scheme author: Tinted Theming (https://github.com/tinted-theming), Ayu Theme (https://github.com/ayu-theme)

# Base16 Ayu Light
# Scheme author: Tinted Theming (https://github.com/tinted-theming), Ayu Theme (https://github.com/ayu-theme)

# Base16 Ayu Light
# Scheme author: Tinted Theming (https://github.com/tinted-theming), Ayu Theme (https://github.com/ayu-theme)

# Base16 Gruvbox light, hard
# Scheme author: Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)

# Base16 Tokyo Night Terminal Storm
# Scheme author: Michaël Ball

# Base16 Catppuccin Latte
# Scheme author: https://github.com/catppuccin/catppuccin

# Base16 Ayu Light
# Scheme author: Tinted Theming (https://github.com/tinted-theming), Ayu Theme (https://github.com/ayu-theme)

# Base16 Ayu Light
# Scheme author: Tinted Theming (https://github.com/tinted-theming), Ayu Theme (https://github.com/ayu-theme)

# Base16 Gruvbox light, hard
# Scheme author: Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)

# Base16 Tokyo Night Light
# Scheme author: Michaël Ball

# Base16 Tokyo Night Light
# Scheme author: Michaël Ball

# Base16 Ayu Light
# Scheme author: Tinted Theming (https://github.com/tinted-theming), Ayu Theme (https://github.com/ayu-theme)

# Base16 Flexoki Light
# Scheme author: 

# Base16 Nord Light
# Scheme author: 

# Base16 Ayu Light
# Scheme author: 

# Base16 Everblush
# Scheme author: 

# Base16 Arc Light
# Scheme author: https://hesamrad.com

# Base16 Flexoki Light
# Scheme author: 

# Base16 Arc Light
# Scheme author: https://hesamrad.com

# Base16 Ayu Light
# Scheme author: 

# Base16 Gruvbox Material Light
# Scheme author: 

# Base16 Everforest Light Hard
# Scheme author: 

# Base16 Ayu Mirage
# Scheme author: 

# Base16 Modus Operandi
# Scheme author: 

# Base16 Arc Light
# Scheme author: https://hesamrad.com

# Base16 Everforest Light Hard
# Scheme author: 

# Base16 Arc Light
# Scheme author: https://hesamrad.com

# Base16 Flexoki Light
# Scheme author: 

# Base16 Harper
# Scheme author: 

# Base16 Paper
# Scheme author: 

# Base16 Hemisu Light
# Scheme author: 

# Base16 Modus Operandi
# Scheme author: 

# Base16 Everforest Light Hard
# Scheme author: 

# Base16 Rosé Pine Dawn
# Scheme author: 

# Base16 Everforest Light Hard
# Scheme author: 

# Base16 Arc Light
# Scheme author: https://hesamrad.com

# Base16 Flexoki Light
# Scheme author: 

# Base16 Ayu Mirage
# Scheme author: 

# Base16 Kanagawa Dragon
# Scheme author: 

# Base16 3024 Night
# Scheme author: 

# Base16 Flexoki Light
# Scheme author: 

# Base16 Gruvbox Material Light
# Scheme author: 

# Base16 Everforest Light Hard
# Scheme author: 

# Base16 Catppuccin Latte
# Scheme author: https://github.com/catppuccin/catppuccin

# Base16 Catppuccin Latte
# Scheme author: https://github.com/catppuccin/catppuccin

# Base16 Nord Light
# Scheme author: 

# Base16 Ayu Light
# Scheme author: 

# Base16 Ayu Light
# Scheme author: Tinted Theming (https://github.com/tinted-theming), Ayu Theme (https://github.com/ayu-theme)

# Base16 Ayu Mirage
# Scheme author: 

# Base16 Flexoki Light
# Scheme author: 

# Base16 Flexoki Light
# Scheme author: 

# Base16 Rosé Pine Dawn
# Scheme author: 

# Base16 Ayu Mirage
# Scheme author: 

# Base16 Gruvbox Material Dark
# Scheme author: 

# Base16 Everforest Dark Hard
# Scheme author: 

# Base16 Ayu Light
# Scheme author: 

# Base16 Modus Vivendi Tinted
# Scheme author: 

# Base16 Rosé Pine Moon
# Scheme author: 

# Base16 Selenized Dark
# Scheme author: 

# Base16 Solarized Dark Higher Contrast
# Scheme author: 

# Base16 Ayu Light
# Scheme author: 

[colors]
background=e8e9eaf2
text=575f66ff
match=399ee6ff
selection=8a9199ff
selection-text=575f66ff
selection-match=399ee6ff
border=399ee6ff
[border]
width=2
radius=10
