[main]
font=IosevkaTermSlab:size=16
width=40
lines=15

# Base16 Catppuccin Mocha
# Scheme author: https://github.com/catppuccin/catppuccin

# Base16 Catppuccin Latte
# Scheme author: https://github.com/catppuccin/catppuccin

# Base16 Nord Light
# Scheme author: 

# Base16 Nord Light
# Scheme author: 

# Base16 Tempus Dawn
# Scheme author: Protesilaos Stavrou (https://protesilaos.com)

# Base16 Papercolor Light
# Scheme author: 

# Base16 Lunaria Light
# Scheme author: 

# Base16 Hemisu Light
# Scheme author: 

# Base16 Ayu Light
# Scheme author: Tinted Theming (https://github.com/tinted-theming), Ayu Theme (https://github.com/ayu-theme)

# Base16 Gruvbox light, hard
# Scheme author: Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)

# Base16 Tokyo Night Light
# Scheme author: Michaël Ball

# Base16 Ayu Light
# Scheme author: Tinted Theming (https://github.com/tinted-theming), Ayu Theme (https://github.com/ayu-theme)

# Base16 Catppuccin Latte
# Scheme author: https://github.com/catppuccin/catppuccin

# Base16 Ayu Light
# Scheme author: Tinted Theming (https://github.com/tinted-theming), Ayu Theme (https://github.com/ayu-theme)

# Base16 Ayu Mirage
# Scheme author: 

# Base16 Gruvbox Material Dark
# Scheme author: 

# Base16 Gruvbox Material Light
# Scheme author: 

# Base16 Hemisu Light
# Scheme author: 

# Base16 Lunaria Light
# Scheme author: 

# Base16 Modus Operandi
# Scheme author: 

# Base16 Modus Operandi Tinted
# Scheme author: 

# Base16 Monokai Pro Light
# Scheme author: 

# Base16 Monokai Pro Light Sun
# Scheme author: 

# Base16 Nord Light
# Scheme author: 

# Base16 Arc Light
# Scheme author: https://hesamrad.com

# Base16 Ayu Light
# Scheme author: 

# Base16 Ayu Mirage
# Scheme author: 

# Base16 Ayu Mirage
# Scheme author: 

# Base16 Everblush
# Scheme author: 

# Base16 Everforest Light Hard
# Scheme author: 

[colors]
background=eeece2f2
text=5c6a72ff
match=3a94c5ff
selection=2e383cff
selection-text=5c6a72ff
selection-match=3a94c5ff
border=3a94c5ff
[border]
width=2
radius=10
